theme: minima
title: MY awesome title
author: stephentwk
email: can I not disclose my email here lol
description: > # this means to ignore newlines until "baseurl:"
  This is my awesome description for my new site here. I can edit this
  line in _config.yml. It will appear in my document head meta (for
  Google search results) and in my feed.xml site description.

# social links
twitter_username: really, twitter? # DO NOT include the @ character, or else the build will fail!
github_username:  stephentwk # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
